import { useMemo, useState } from 'react';
import { AlertTriangle, ArrowRight, Fingerprint, Radar, Search, ShieldAlert, ShieldCheck } from 'lucide-react';
import { analyzeCyberDocument, DEMO_RECORDS } from '@/services/cyberIntel';
export function CyberIntelligencePage({ source, notify }) {
    const [query, setQuery] = useState('');
    const [selected, setSelected] = useState(null);
    const match = useMemo(() => source ? analyzeCyberDocument(source.rawText, source.sourceName, source.docId) : null, [source]);
    const active = selected ?? match;
    const run = () => { const result = analyzeCyberDocument(query, 'manual local query', source?.docId ?? 'other'); setSelected(result); notify(result.matched ? 'Demo record match found in Cyber Intelligence' : 'No demo record match returned'); };
    return <div className="space-y-7">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><div className="label-caps">Identity / case intelligence</div><h1 className="mt-2 font-display text-3xl font-extrabold">The context layer, kept apart.</h1><p className="mt-2 max-w-2xl text-sm text-slate-500">This surface owns identity, correlation, and case details. It reads the latest verification locally and never changes the document result.</p></div><div className="flex items-center gap-2 rounded-xl border border-slate-300 bg-white/65 px-3 py-2 text-xs font-bold text-slate-600"><Radar size={15}/> Fictional local index</div></div>
    <div className="data-grid"><div className="span-4 surface rounded-2xl p-5"><div className="label-caps">Search local demo index</div><h2 className="mt-2 font-display text-lg font-extrabold">Correlate a subject</h2><p className="mt-2 text-xs leading-relaxed text-slate-500">Try a fictional name from the test index, such as “Parth Raivansh”.</p><div className="relative mt-5"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={15}/><input data-testid="input-cyber-query" className="field pl-9" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Name or demo identifier"/></div><button data-testid="button-run-cyber-search" className="matte-button primary mt-3 w-full" onClick={run} disabled={!query.trim()}><Fingerprint size={15}/> Run local correlation</button><div className="mt-5 border-t border-slate-200 pt-4"><div className="label-caps">Index profiles</div><div className="mt-3 flex flex-wrap gap-2">{DEMO_RECORDS.map((record) => <button key={record.id} className="rounded-full border border-slate-300 bg-white/70 px-2.5 py-1.5 text-[10px] font-bold text-slate-600 hover:bg-slate-100" onClick={() => { setQuery(record.name); setSelected(analyzeCyberDocument(record.name, record.id, source?.docId ?? 'other')); }}>{record.name}</button>)}</div></div></div>
    <div className="span-8 space-y-4">{!active ? <div className="surface-quiet flex min-h-[340px] flex-col items-center justify-center rounded-2xl border-dashed text-center text-slate-400"><ShieldAlert size={38} strokeWidth={1.2}/><p className="mt-3 text-sm font-bold">No identity context yet</p><p className="mt-1 max-w-sm text-xs">Verify a document or search the fictional local index to open an intelligence case.</p></div> : <CyberResult match={active}/>}</div></div>
    <div className="surface rounded-2xl p-4 text-xs leading-relaxed text-slate-500"><b className="text-slate-700">Guardrail.</b> Demo records are fictional test profiles. A matched demo record intentionally uses a soft red surface here only. Verification itself remains neutral and document-only.</div>
  </div>;
}
function CyberResult({ match }) {
    return <div className={`surface rounded-2xl p-5 sm:p-6 ${match.matched ? 'soft-red-surface' : ''}`}><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex items-center gap-3"><div className={`flex h-12 w-12 items-center justify-center rounded-2xl ${match.matched ? 'bg-[#f1cbd1] text-[#a9364b]' : 'bg-[#e5f4ec] text-[#1f8a5a]'}`}>{match.matched ? <ShieldAlert size={25}/> : <ShieldCheck size={25}/>}</div><div><div className="label-caps">Correlation result</div><h2 className="mt-1 font-display text-2xl font-extrabold">{match.matched ? 'High-confidence record match' : 'No record match'}</h2><p className="mt-1 text-xs text-slate-500">{match.note}</p></div></div><span className={`status-pill ${match.matched ? 'failed' : 'verified'}`}>{match.matched ? 'Manual review' : 'No match'}</span></div><div className="mt-6 grid gap-3 sm:grid-cols-3">{[['Identity subject', match.subject.name], ['Date of birth', match.subject.dob], ['Document reference', match.subject.document]].map(([label, value]) => <div key={label} className="rounded-xl border border-black/5 bg-white/55 p-3"><div className="label-caps">{label}</div><div className="mt-2 text-sm font-bold">{value}</div></div>)}</div><div className="mt-5 grid gap-4 sm:grid-cols-2"><div className="rounded-xl border border-black/5 bg-white/55 p-4"><div className="mb-3 flex items-center gap-2 text-sm font-bold"><Radar size={15}/> Signal confidence</div><Score label="Name correlation" value={match.metrics.name}/><Score label="Date correlation" value={match.metrics.dob}/><Score label="Document correlation" value={match.metrics.document}/><Score label="Face region signal" value={match.metrics.face}/></div>{match.record ? <div className="rounded-xl border border-[#e6b8c0] bg-[#fbecee]/70 p-4"><div className="mb-3 flex items-center gap-2 text-sm font-bold text-[#873446]"><AlertTriangle size={15}/> Case details</div><div className="space-y-2 text-xs text-slate-600"><Row label="Record ID" value={match.record.id}/><Row label="Case" value={match.record.caseNo}/><Row label="Court" value={match.record.court}/><Row label="Status" value={match.record.status}/><Row label="Category" value={match.record.category}/></div><button className="matte-button danger mt-4 w-full"><ArrowRight size={14}/> Open protected case view</button></div> : <div className="rounded-xl border border-black/5 bg-white/55 p-4"><div className="mb-3 flex items-center gap-2 text-sm font-bold text-[#1f8a5a]"><ShieldCheck size={15}/> Clean local context</div><p className="text-xs leading-relaxed text-slate-500">No sufficiently correlated fictional case was returned. Keep using the document result as the source of truth.</p></div>}</div></div>;
}
function Score({ label, value }) { return <div className="mb-3 last:mb-0"><div className="flex justify-between text-xs"><span className="text-slate-500">{label}</span><b className="font-mono">{value}%</b></div><div className="mt-1.5 h-1.5 rounded-full bg-slate-200"><div className="h-full rounded-full bg-[#536b80]" style={{ width: `${value}%` }}/></div></div>; }
function Row({ label, value }) { return <div className="flex justify-between gap-3"><span className="text-slate-400">{label}</span><b className="text-right">{value}</b></div>; }
