import { ArrowRight, Upload } from 'lucide-react';
import { DOCUMENT_TYPES } from '@/utils/documentRules';
import { Icon } from '@/components/Icon';
export function DashboardPage({ history, onView, onSelectDoc }) {
    const valid = history.filter((item) => item.status === 'VERIFIED').length;
    const invalid = history.filter((item) => item.status === 'FAILED').length;
    const review = history.filter((item) => item.status === 'NEEDS_REVIEW').length;
    const rate = history.length ? Math.round(valid / history.length * 100) : 0;
    return <div className="space-y-7">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><div className="label-caps">Overview / Today</div><h1 className="mt-2 font-display text-3xl font-extrabold tracking-tight">Quiet confidence, one file at a time.</h1><p className="mt-2 max-w-2xl text-sm text-slate-500">Review documents locally, preserve the evidence trail, and keep identity details in the intelligence lane.</p></div><button data-testid="button-dashboard-scan" className="matte-button primary" onClick={() => onView('smartscan')}><Upload size={15}/> Start a Smart Scan</button></div>
    <div className="data-grid"><Metric label="Documents valid" value={valid} icon="ShieldCheck" tone="positive"/><Metric label="Fraud detected" value={invalid} icon="ShieldX" tone="danger"/><Metric label="Needs review" value={review} icon="ShieldAlert" tone="warning"/><Metric label="Success rate" value={`${rate}%`} icon="Gauge" tone="neutral"/></div>
    <div className="surface rounded-2xl p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="label-caps">Universal intake</div><h2 className="mt-2 font-display text-xl font-extrabold">Smart Scan any document</h2><p className="mt-1 text-sm text-slate-500">Drop mixed images or PDFs and route every page through browser OCR and document classification.</p></div><button className="matte-button secondary" onClick={() => onView('smartscan')}>Open Smart Scan <ArrowRight size={15}/></button></div><div className="mt-5 grid gap-3 sm:grid-cols-3">{[['OCR', 'Read visible fields in the browser'], ['CLASSIFY', 'Suggest the right document lane'], ['VERIFY', 'Keep only the result in this surface']].map(([title, text]) => <div key={title} className="surface-quiet rounded-xl p-4"><div className="font-mono text-[10px] font-bold tracking-[.15em] text-slate-400">{title}</div><p className="mt-2 text-sm font-semibold text-slate-600">{text}</p></div>)}</div></div>
    <section><div className="mb-4 flex items-center justify-between"><div><div className="label-caps">Verification lanes</div><h2 className="mt-1 font-display text-xl font-extrabold">Select a document type</h2></div><span className="text-xs text-slate-500">{DOCUMENT_TYPES.length} supported categories</span></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{DOCUMENT_TYPES.map((doc) => <div key={doc.id} className="surface rounded-2xl p-4 transition-transform hover:-translate-y-0.5"><div className="flex items-start justify-between"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#e6edf2] text-[#50677c]"><Icon name={doc.id === 'aadhaar' ? 'CreditCard' : doc.id === 'pan' ? 'Database' : doc.id === 'passport' ? 'BookOpen' : doc.id === 'dl' ? 'FileCheck2' : 'FileText'} size={19}/></div><span className="font-mono text-[9px] text-slate-400">{doc.id.toUpperCase()}</span></div><h3 className="mt-4 text-sm font-bold">{doc.name}</h3><p className="mt-1 min-h-10 text-xs leading-relaxed text-slate-500">{doc.description}</p><button data-testid={`button-verify-${doc.id}`} className="matte-button ghost mt-3 w-full justify-between border-t border-slate-200 pt-3" onClick={() => { onSelectDoc(doc.id); onView('verify'); }}>Verify this type <ArrowRight size={14}/></button></div>)}</div></section>
  </div>;
}
function Metric({ label, value, icon, tone }) {
    return <div className="surface rounded-2xl p-4"><div className="flex items-center justify-between"><div className={`flex h-9 w-9 items-center justify-center rounded-xl ${tone === 'positive' ? 'bg-[#e4f3ea] text-[#1f8a5a]' : tone === 'danger' ? 'bg-[#fae8eb] text-[#ac3348]' : tone === 'warning' ? 'bg-[#fbf0dc] text-[#a86d19]' : 'bg-[#e8edf2] text-[#536b80]'}`}><Icon name={icon} size={17}/></div><span className="font-mono text-[9px] text-slate-400">LOCAL</span></div><div className="mt-5 font-display text-2xl font-extrabold">{value}</div><div className="mt-1 text-xs font-semibold text-slate-500">{label}</div></div>;
}
