import { Search } from 'lucide-react';
import { useMemo, useState } from 'react';
import { StatusPill, RiskPill } from '@/components/StatusPill';
const seeds = [
    { id: 'seed-1', createdAt: '26 Aug 2026 · 09:42', docId: 'aadhaar', sourceName: 'aadhaar-sample.jpg', detected: 'Aadhaar Card', status: 'VERIFIED', headline: 'VERIFIED', confidence: 95, issues: [], why: [], risk: { level: 'LOW', reasons: [] }, recommendation: '', rawText: '', caseId: 'VR-1042', identityCode: 'ZID-DEMO-1042', riskPercent: 8 },
    { id: 'seed-2', createdAt: '25 Aug 2026 · 16:18', docId: 'pan', sourceName: 'pan-sample.png', detected: 'PAN Card', status: 'FAILED', headline: 'INVALID NUMBER FORMAT', confidence: null, issues: [{ title: 'Document mismatch', severity: 'HIGH', detail: '' }], why: [], risk: { level: 'HIGH', reasons: [] }, recommendation: '', rawText: '', caseId: 'VR-1043', identityCode: 'ZID-DEMO-1043', riskPercent: 76 },
];
export function HistoryPage({ history }) {
    const [query, setQuery] = useState('');
    const rows = useMemo(() => [...history, ...seeds].filter((item) => `${item.detected} ${item.sourceName} ${item.caseId}`.toLowerCase().includes(query.toLowerCase())), [history, query]);
    return <div className="space-y-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><div className="label-caps">Audit trail / Local session</div><h1 className="mt-2 font-display text-3xl font-extrabold">Every attempt, visible.</h1><p className="mt-2 text-sm text-slate-500">A compact record of document outcomes. Identity and case detail stay out of this table.</p></div><div className="relative w-full sm:w-64"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={15}/><input data-testid="input-history-search" className="field pl-9" placeholder="Search history" value={query} onChange={(event) => setQuery(event.target.value)}/></div></div><div className="surface overflow-x-auto rounded-2xl"><table className="w-full min-w-[720px] text-left"><thead className="border-b border-slate-200 bg-[#f1f4f6] text-[10px] uppercase tracking-[.12em] text-slate-500"><tr><th className="px-5 py-4">Date</th><th className="px-5 py-4">Document</th><th className="px-5 py-4">Source</th><th className="px-5 py-4">Result</th><th className="px-5 py-4">Risk</th><th className="px-5 py-4">Reference</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id} className="border-b border-slate-100 last:border-0"><td className="px-5 py-4 text-xs text-slate-500">{row.createdAt}</td><td className="px-5 py-4 text-sm font-bold">{row.detected}</td><td className="max-w-[190px] truncate px-5 py-4 text-xs text-slate-500">{row.sourceName}</td><td className="px-5 py-4"><StatusPill status={row.status}/></td><td className="px-5 py-4"><div className="flex items-center gap-2"><RiskPill level={row.risk.level}/><span className="font-mono text-[10px] text-slate-500">{row.riskPercent}%</span></div></td><td className="px-5 py-4 font-mono text-[10px] text-slate-500">{row.caseId}</td></tr>)}</tbody></table>{rows.length === 0 && <div className="p-12 text-center text-sm text-slate-500">No matching verification attempts.</div>}</div></div>;
}
