import { ArrowRight, FileCheck2, LockKeyhole, ScanLine, ShieldCheck } from 'lucide-react';
import { Icon } from '@/components/Icon';
export function Landing({ onStart }) {
    return <div className="zyid-app relative overflow-hidden">
    <div className="absolute -left-24 -top-24 h-72 w-72 rounded-full bg-[#c9d8e4]/55 blur-3xl"/><div className="absolute -bottom-32 right-0 h-96 w-96 rounded-full bg-[#bac6d0]/50 blur-3xl"/>
    <main className="relative z-10 mx-auto flex min-h-[100dvh] w-full max-w-7xl flex-col px-[clamp(1.25rem,5vw,5.5rem)] py-6">
      <header className="flex items-center justify-between"><div className="flex items-center gap-2.5"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#344252] text-white shadow-lg"><span className="font-display text-xl font-extrabold">Z</span></div><div className="font-display text-xl font-extrabold">ZyID</div></div><span className="rounded-full border border-slate-300 bg-white/60 px-3 py-1.5 text-[10px] font-bold uppercase tracking-[.15em] text-slate-500">Local verification workspace</span></header>
      <section className="grid flex-1 items-center gap-12 py-16 lg:grid-cols-[1.05fr_.95fr] lg:gap-20">
        <div><div className="mb-5 flex items-center gap-2 label-caps"><span className="h-px w-8 bg-[#7f97a9]"/> Matte intelligence suite</div><h1 className="max-w-3xl font-display text-[clamp(3.2rem,8vw,7.8rem)] font-extrabold leading-[.9] tracking-[-.07em] text-[#1a2939]">Scan.<br /><span className="text-[#6b7e90]">Verify.</span><br />Protect.</h1><p className="mt-8 max-w-xl text-[clamp(1rem,1.5vw,1.2rem)] leading-relaxed text-slate-600">A focused browser workspace for document verification, multi-file screening, and case intelligence. Files never leave this device.</p><div className="mt-9 flex flex-wrap items-center gap-3"><button data-testid="button-start-workspace" className="matte-button primary px-5" onClick={onStart}>Open local workspace <ArrowRight size={16}/></button><span className="flex items-center gap-2 text-xs font-bold text-slate-500"><LockKeyhole size={14}/> No account. No cloud.</span></div></div>
        <div className="surface relative rounded-[28px] p-5 sm:p-7"><div className="absolute -right-5 -top-5 rounded-2xl bg-[#344252] px-3 py-2 text-[10px] font-bold uppercase tracking-[.14em] text-white shadow-xl">Browser / 01</div><div className="rounded-2xl border border-slate-300 bg-[#eef2f5] p-4 sm:p-6"><div className="flex items-center justify-between border-b border-slate-300 pb-4"><div className="flex items-center gap-2 text-xs font-bold text-slate-600"><ScanLine size={15}/> Intake monitor</div><span className="font-mono text-[10px] text-slate-400">READY</span></div><div className="grid gap-3 py-6 sm:grid-cols-[.75fr_1.25fr]"><div className="flex aspect-[.78] items-center justify-center rounded-xl border border-slate-300 bg-white"><FileCheck2 className="text-[#5f7385]" size={42} strokeWidth={1.2}/></div><div className="space-y-3"><div className="h-3 w-28 rounded bg-[#c0ccd5]"/><div className="h-2 w-full rounded bg-[#d5dde4]"/><div className="h-2 w-4/5 rounded bg-[#d5dde4]"/><div className="mt-6 border-t border-slate-300 pt-4"><div className="flex items-center gap-2 text-sm font-bold text-[#35516a]"><ShieldCheck size={16}/> Structure matched</div><div className="mt-2 font-mono text-[10px] text-slate-500">RISK SIGNAL <b className="text-[#1f8a5a]">08%</b></div></div></div></div></div><div className="mt-5 grid grid-cols-3 gap-2">{[['01', 'OCR'], ['02', 'FORMAT'], ['03', 'REPORT']].map(([n, l]) => <div key={n} className="rounded-xl border border-slate-200 bg-white/70 p-3"><div className="font-mono text-[10px] text-slate-400">{n}</div><div className="mt-2 text-xs font-bold">{l}</div></div>)}</div></div>
      </section>
      <footer className="flex flex-wrap items-center gap-6 border-t border-slate-300/70 pt-5 text-xs font-semibold text-slate-500"><span className="flex items-center gap-2"><Icon name="ShieldCheck" size={14}/> Local-first verification</span><span className="flex items-center gap-2"><Icon name="FileStack" size={14}/> Multi-document ready</span><span className="flex items-center gap-2"><Icon name="Database" size={14}/> Persistent in browser</span></footer>
    </main>
  </div>;
}
