import { useEffect, useState } from 'react';
import { Moon, Palette, Sun, Trash2 } from 'lucide-react';
import { clearLocalData } from '@/services/localStore';
export function SettingsPage({ notify, onClear }) {
    const [dark, setDark] = useState(() => localStorage.getItem('zyid-theme-mode') === 'dark');
    useEffect(() => { document.documentElement.classList.toggle('dark', dark); document.body.classList.toggle('zyid-dark', dark); localStorage.setItem('zyid-theme-mode', dark ? 'dark' : 'light'); }, [dark]);
    const wipe = () => { clearLocalData(); onClear(); notify('Local verification history and stored reports cleared'); };
    return <div className="space-y-7"><div><div className="label-caps">Workspace controls</div><h1 className="mt-2 font-display text-3xl font-extrabold">Keep the surface yours.</h1><p className="mt-2 text-sm text-slate-500">Appearance and privacy controls apply only to this browser.</p></div><div className="data-grid"><div className="span-7 surface rounded-2xl p-5 sm:p-7"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#e8edf1] text-[#536b80]"><Palette size={20}/></div><div><h2 className="font-display text-xl font-extrabold">Appearance</h2><p className="mt-1 text-xs text-slate-500">Light is the default ZyID matte workspace.</p></div></div><div className="mt-6 flex items-center justify-between rounded-xl border border-slate-200 bg-[#f2f5f7] p-4"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-lg bg-white">{dark ? <Moon size={17}/> : <Sun size={17}/>}</div><div><div className="text-sm font-bold">{dark ? 'Dark contrast' : 'Matte light'}</div><div className="text-xs text-slate-500">Saved as a local preference</div></div></div><button className="matte-button secondary" onClick={() => setDark((value) => !value)}>{dark ? 'Use light' : 'Use dark'}</button></div></div><div className="span-5 surface rounded-2xl p-5 sm:p-7"><div className="flex items-center gap-2 text-sm font-bold"><Trash2 size={16}/> Local data</div><p className="mt-3 text-xs leading-relaxed text-slate-500">Clear verification history and stored screening reports from this browser. This cannot be undone.</p><button className="matte-button danger mt-5 w-full" onClick={wipe}>Clear local data</button></div></div></div>;
}
